version: "3.8"

services:
  app:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    container_name: task-api
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=${PORT}
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - task-network

  db:
    image: mysql:8.0
    container_name: task-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - task-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db-data:

networks:
  task-network:
