name: Build and Deploy

on:
  workflow_call:
  # This allows the workflow to be called from other workflows

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    # [Previous build steps remain unchanged]

  deploy:
    name: Deploy with Terraform
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

      - name: Terraform Plan
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
          # Convert string to proper type for Terraform
          ALLOCATED_STORAGE: ${{ secrets.ALLOCATED_STORAGE }}
          MAX_ALLOCATED_STORAGE: ${{ secrets.MAX_ALLOCATED_STORAGE }}
          MULTI_AZ: ${{ secrets.MULTI_AZ }}
        run: |
          # Convert string values to proper types for Terraform
          allocated_storage=$(echo $ALLOCATED_STORAGE | tr -d '"')
          max_allocated_storage=$(echo $MAX_ALLOCATED_STORAGE | tr -d '"')
          multi_az=$(echo $MULTI_AZ | tr '[:upper:]' '[:lower:]')
          
          terraform plan \
          -var="docker_image=${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}" \
          -var="db_name=${{ secrets.DB_NAME }}" \
          -var="aws_region=${{ secrets.AWS_REGION }}" \
          -var="db_instance_class=${{ secrets.DB_INSTANCE_CLASS }}" \
          -var="allocated_storage=${allocated_storage}" \
          -var="max_allocated_storage=${max_allocated_storage}" \
          -var="multi_az=${multi_az}" \
          -out=tfplan
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform
